import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
let now = 0;
const context = vm.createContext({window: {}, Date: {now: () => now}});
vm.runInContext(fs.readFileSync(new URL('../js/cache-manager.js', import.meta.url), 'utf8'), context);
const cache = context.window.cacheManager;
cache.set('short', 'short', 1000);
cache.set('long', 'long', 5000);
now = 1000;
assert.equal(cache.get('short'), null);
assert.equal(cache.get('long'), 'long');
cache.setCacheDuration('long', 2000);
now = 2000;
assert.equal(cache.get('long'), null);
let calls = 0;
await Promise.all([cache.fetchWithCache('dedupe', () => ++calls), cache.fetchWithCache('dedupe', () => ++calls)]);
assert.equal(calls, 1);
let resolve;
const oldAccount = cache.fetchWithCache('private', () => new Promise(r => {resolve = r;}));
await Promise.resolve();
cache.clear();
resolve('old-account');
await oldAccount;
assert.equal(cache.get('private'), null);
await assert.rejects(cache.fetchWithCache('failure', () => Promise.reject(new Error('network'))));
assert.equal(cache.pending.size, 0);
await cache.fetchWithCache('api-error', () => ({error: {message: 'denied'}}));
assert.equal(cache.get('api-error'), null);
console.log('Cache tests passed: per-key TTL, boundary, deduplication, failure, account isolation.');
